### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by navierula** [Shikuchiki/intro-data-capstone-biodiversity#1]
Hi @Shikuchiki. I know you completed the coding portion in the environment, but you'd still need to upload your work here in some way so I can review your code in addition to your presentation. Thanks!

**Comment by Shikuchiki** [comment]
Hi, @navierula I was just following the instructions per discussion on slack and was under the impression that the code need not be uploaded if completed in the online learning environment? Did you want me to just copy and paste out the code from the learning environment and upload it?

**Comment by navierula** [comment]
Hi @Shikuchiki. Thanks for letting me know, but in order for me to review, I would need to see your code. You can upload it in a `.py` file, `.ipynb` file, etc. Whatever you language you coded in, whatever you prefer. Copy and paste is fine.
